language: node_js
dist: trusty
sudo: required
node_js: 8
script: npm test
cache:
  directories:
  - node_modules
env:
  global:
  - VISUAL_RECOGNITION_API_KEY="bogus key to let server spin up for offline tests"
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8